// Builds the Codex-style icon set (icons/codex-icons.mjs) into theme.css and writes
// icons/preview.html for checking the set by eye. Run with `npm run icons`.
//
// Each icon becomes a CSS mask on Obsidian's own <svg class="svg-icon lucide-…">: the Lucide
// paths are hidden and the svg box is painted in currentcolor through the mask, so the
// replacement shows up everywhere Obsidian draws that icon – menus, tabs, the file tree, callouts.

import { readFileSync, writeFileSync } from 'node:fs';
import { icons } from '../icons/codex-icons.mjs';

const STROKE = 1.6;
const START = '/* @inlay-icons:start – generated by scripts/build-icons.mjs, do not edit by hand */';
const END = '/* @inlay-icons:end */';

// Obsidian's own icons carry their bare id as the class; Lucide icons get a `lucide-` prefix
const OBSIDIAN_IDS = new Set(['help', 'right-triangle', 'links-coming-in', 'links-going-out', 'sidebar-toggle-button-icon', 'sidebar-left', 'sidebar-right', 'document', 'vault']);
const classesOf = (id) => OBSIDIAN_IDS.has(id) ? [id, `lucide-${id}`] : [`lucide-${id}`];

const svg = (body) => `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' stroke-width='${STROKE}' stroke-linecap='round' stroke-linejoin='round'>${body}</svg>`;
const dataUri = (body) => `url("data:image/svg+xml,${encodeURIComponent(svg(body)).replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/').replace(/%2C/g, ',')}")`;

const seen = new Map();
for (const icon of icons) {
	for (const id of icon.ids) {
		if (seen.has(id)) throw new Error(`icon id "${id}" is defined twice`);
		seen.set(id, icon);
	}
}

const allClasses = [...seen.keys()].flatMap(classesOf);
const lines = [];
lines.push(START);
lines.push(':is(body.inlay-codex-icons, body.inlay-codex-rail .workspace-ribbon) svg.svg-icon {');
lines.push(`\t&:is(${allClasses.map((c) => `.${c}`).join(', ')}) {`);
lines.push('\t\tbackground-color: currentcolor;');
lines.push('\t\tmask: var(--inlay-icon) center / contain no-repeat;');
lines.push('');
lines.push('\t\t& > * {');
lines.push('\t\t\tdisplay: none;');
lines.push('\t\t}');
lines.push('\t}');
for (const icon of icons) {
	const selector = icon.ids.flatMap(classesOf).map((c) => `&.${c}`).join(', ');
	lines.push('');
	lines.push(`\t${selector} {`);
	lines.push(`\t\t--inlay-icon: ${dataUri(icon.body)};`);
	lines.push('\t}');
	if (icon.filled) {
		const filledSelector = icon.ids.flatMap(classesOf).map((c) => `.mod-filled > &.${c}`).join(', ');
		lines.push('');
		lines.push(`\t${filledSelector} {`);
		lines.push(`\t\t--inlay-icon: ${dataUri(icon.filled)};`);
		lines.push('\t}');
	}
}
lines.push('}');
lines.push('');
lines.push(END);
const block = lines.join('\n');

const themePath = new URL('../theme.css', import.meta.url);
const theme = readFileSync(themePath, 'utf8');
const from = theme.indexOf(START);
const to = theme.indexOf(END);
if (from === -1 || to === -1) throw new Error('theme.css is missing the @inlay-icons markers');
writeFileSync(themePath, theme.slice(0, from) + block + theme.slice(to + END.length));

const attr = (body) => dataUri(body).replace(/"/g, '&quot;');
const cells = icons.map((icon) => `<figure><div class="row"><span style="--i:${attr(icon.body)}" class="s16"></span><span style="--i:${attr(icon.body)}" class="s20"></span><span style="--i:${attr(icon.body)}" class="s32"></span></div><figcaption>${icon.ids.join(' · ')}</figcaption></figure>`).join('\n');
writeFileSync(new URL('../icons/preview.html', import.meta.url), `<!doctype html>
<meta charset="utf-8">
<title>Inlay – Codex icon set</title>
<style>
	body { margin: 24px; font: 11px/1.4 -apple-system, system-ui, sans-serif; color: #5d5d5d; background: #fff; }
	@media (prefers-color-scheme: dark) { body { background: #1c1c1c; color: #b3b3b3; } }
	main { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 8px; }
	figure { margin: 0; padding: 12px 8px; border-radius: 10px; text-align: center; }
	figure:hover { background: color-mix(in srgb, currentcolor 8%, transparent); }
	.row { display: flex; gap: 14px; align-items: center; justify-content: center; height: 36px; }
	span { display: block; background: currentcolor; mask: var(--i) center / contain no-repeat; }
	.s16 { width: 16px; height: 16px; } .s20 { width: 20px; height: 20px; } .s32 { width: 32px; height: 32px; }
	figcaption { margin-top: 6px; word-break: break-word; }
</style>
<h1 style="font-size:14px">Inlay – Codex icon set · ${icons.length} glyphs · ${seen.size} ids</h1>
<main>
${cells}
</main>
`);

console.log(`${icons.length} glyphs, ${seen.size} icon ids → theme.css, icons/preview.html`);
